Feat/rishabh winner history
jkcsoftwaresllp/CasGamPro_client pull request #11
Opened 2024-12-27 07:06 UTC by rishxbh81

## Description

winner history component is ready

## Related Issue(s)

If applicable, please link any issues that this PR addresses (e.g., `Closes #123`, `Fixes #456`).

- Issue(s) resolved: [link issues here]

## Type of Change

Please select the appropriate category for this PR:

- [ ] **Bug Fix** – Non-breaking changes that resolve issues
- [ ] **New Feature** – Additions or enhancements to functionality
- [ ] **Refactor** – Code changes that improve readability or maintainability
- [ ] **Documentation** – Updates or additions to documentation
- [ ] **Tests** – Changes related to test coverage or testing strategy
- [ ] **Chore** – Other changes (e.g., maintenance, dependency updates)

## Checklist

Please make sure the following steps are completed before submitting your PR:

- [ ] I have tested the code changes locally.
- [ ] I have update/added the documentation/`readme.draft.md` (if applicable).
- [ ] I have added/updated tests (if applicable).
- [ ] My changes do not break existing functionality.
- [ ] I have rebased the branch with the latest version of the `development` branch.
- [ ] The PR title is descriptive and follows the project's naming conventions.
- [ ] The PR description is clear and includes all necessary information.

## Reviewer(s)

Please tag the appropriate reviewers for this PR:

- @Danishan2 

### _JKC Softwares LLP_

2024-12-27 07:29 UTC, Danishan2 commented on src/components/GameComponents/PlaceStake/PlaceStake.jsx
This File has nothing

2024-12-27 07:30 UTC, Danishan2 commented on src/components/GameComponents/WinnerHistory/WinnerBox.jsx
> +const WinnerBox = ({ winner }) => {
Refactored component to accept `winnerName`, `roundId`, and `onClick` as props for better reusability and dynamic rendering.

2024-12-27 07:32 UTC, Danishan2 commented on src/components/GameComponents/WinnerHistory/WinnerHistory.jsx
> +const WinnerHistory = () => {
Refactored component to accept `GameId`, as props for better dynamic rendering.

2024-12-27 07:34 UTC, Danishan2 requested changes
Complete the suggested Changes

2024-12-28 12:40 UTC, Danishan2 approved these changes

2024-12-28 12:42 UTC, Danishan2 approved these changes

2024-12-28 12:43 UTC, merged

2024-12-28 13:26 UTC, rishxbh81 commented on src/components/GameComponents/WinnerHistory/WinnerBox.jsx
> +const WinnerBox = ({ winner }) => {
changes has been made

2024-12-28 13:34 UTC, rishxbh81 commented on src/components/GameComponents/WinnerHistory/WinnerHistory.jsx
> +const WinnerHistory = () => {
done